using System.Collections.Concurrent;
using System.Threading;
using MauiApp1.ApplicationContracts.Repositories;
using MauiApp1.ApplicationContracts.Services;
using MauiApp1.Models;
using System.Diagnostics;
using Microsoft.Extensions.Logging;

namespace MauiApp1.Services;

public sealed class PoiTranslationService : IPoiTranslationService
{
    private readonly IPoiQueryRepository _poiQuery;
    private readonly ITranslationRepository _translationCache;
    private readonly ITranslationProvider _translator;
    private readonly ILocalizationService _locService;
    private readonly ILogger<PoiTranslationService> _logger;
    private readonly IEventTracker _eventTracker;
    private readonly IUserContextSnapshotProvider _userContext;
    private readonly TranslationTrackingSession _trackingSession;

    private static string NormalizeLang(string? lang) =>
        string.IsNullOrWhiteSpace(lang) ? "vi" : lang.Trim().ToLowerInvariant();

    private readonly ConcurrentDictionary<string, SemaphoreSlim> _locks = new();
    private readonly SemaphoreSlim _globalLimit = new SemaphoreSlim(3);

    public PoiTranslationService(
        IPoiQueryRepository poiQuery,
        ITranslationRepository translationCache,
        ITranslationProvider translator,
        ILocalizationService locService,
        ILogger<PoiTranslationService> logger,
        IEventTracker eventTracker,
        IUserContextSnapshotProvider userContext,
        TranslationTrackingSession trackingSession)
    {
        _poiQuery = poiQuery;
        _translationCache = translationCache;
        _translator = translator;
        _locService = locService;
        _logger = logger;
        _eventTracker = eventTracker;
        _userContext = userContext;
        _trackingSession = trackingSession;
    }

    /// <inheritdoc />
    public async Task<Poi?> GetOrTranslateAsync(string code, string? lang, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(code))
            return null;

        code = code.Trim().ToUpperInvariant();

        await _poiQuery.InitAsync(cancellationToken).ConfigureAwait(false);

        var targetLang = NormalizeLang(lang);

        // 1) Exact row in main POI table (same behavior as "have this language" without touching fallback order here)
        var direct = await _poiQuery.GetExactByCodeAndLanguageAsync(code, targetLang, cancellationToken).ConfigureAwait(false);
        if (direct != null)
            return direct;

        var key = PoiTranslationCacheEntry.MakeKey(code, targetLang);
        Debug.WriteLine($"[TRANSLATE] GetOrTranslateAsync start code={code} target={targetLang}");
        var gate = _locks.GetOrAdd(key, _ => new SemaphoreSlim(1, 1));
        var entered = false;
        await gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        entered = true;
        try
        {
            cancellationToken.ThrowIfCancellationRequested();

            // 2) Re-check primary table (another thread may have inserted)
            direct = await _poiQuery.GetExactByCodeAndLanguageAsync(code, targetLang, cancellationToken).ConfigureAwait(false);
            if (direct != null)
                return direct;

            // 3) Cache
            var cached = await _translationCache.GetTranslationCacheAsync(code, targetLang, cancellationToken).ConfigureAwait(false);
            if (cached != null)
            {
                Debug.WriteLine($"[TRANSLATE] Cache hit key={cached.Key}");
                var sourceForGeo = await GetTranslationSourcePoiAsync(code, cancellationToken).ConfigureAwait(false);
                if (sourceForGeo == null)
                    return null;
                await TrackTranslationCacheHitAsync(sourceForGeo, code, targetLang, cancellationToken).ConfigureAwait(false);
                return MergeCachedTextWithSourcePoi(sourceForGeo, cached, targetLang, cached.IsAutoGenerated);
            }
            Debug.WriteLine($"[TRANSLATE] Cache miss key={key}");

            // 4) Source POI: prefer EN, else any row for code
            var source = await GetTranslationSourcePoiAsync(code, cancellationToken).ConfigureAwait(false);
            if (source == null)
                return null;

            var fromLang = source.Localization?.LanguageCode ?? "vi"; 
            if (fromLang == targetLang)
                return source;

            Debug.WriteLine($"[TRANSLATE] Translating code={code} from={fromLang} to={targetLang}");

            var srcLoc = source.Localization;
            if (srcLoc == null)
            {
                Debug.WriteLine($"[TRANSLATE] Source localization is null for {code}, using empty strings");
                srcLoc = new PoiLocalization { Name = "", Summary = "", NarrationShort = "", NarrationLong = "" };
            }

            var entry = await ExecuteTranslationBatchAsync(code, fromLang, targetLang, srcLoc, cancellationToken).ConfigureAwait(false);
            if (entry == null) return null;

            if (entry.IsAutoGenerated)
            {
                Debug.WriteLine($"[TRANSLATE] All segments succeeded, caching key={key}");
                await _translationCache.UpsertTranslationCacheAsync(entry, cancellationToken).ConfigureAwait(false);
            }
            else
            {
                Debug.WriteLine($"[TRANSLATE] Partial/failed translation for code={code} to {targetLang}; skipping cache");
            }

            Debug.WriteLine($"[TRANSLATE] Returning merged poi for code={code} target={targetLang} succeeded={entry.IsAutoGenerated}");
            return MergeCachedTextWithSourcePoi(source, entry, targetLang, entry.IsAutoGenerated);
        }
        finally
        {
            if (entered)
            {
                try { gate.Release(); } catch { }
            }
        }
    }

    private static Poi MergeCachedTextWithSourcePoi(Poi source, PoiTranslationCacheEntry cached, string targetLang, bool isAutoTranslated)
    {
        var poi = new Poi
        {
            Id = $"{source.Code.Trim()}_{targetLang}",
            Code = source.Code.Trim(),
            Latitude = source.Latitude,
            Longitude = source.Longitude,
            Radius = source.Radius,
            Priority = source.Priority,
            IsAutoTranslated = isAutoTranslated,
            Localization = new PoiLocalization
            {
                Code = source.Code.Trim(),
                LanguageCode = targetLang,
                Name = cached.Name,
                Summary = cached.Summary,
                NarrationShort = cached.NarrationShort,
                NarrationLong = cached.NarrationLong
            }
        };

        return poi;
    }

    private async Task TrackTranslationCacheHitAsync(Poi geoPoi, string code, string targetLang, CancellationToken cancellationToken)
    {
        try
        {
            var ctx = await _userContext.GetAsync(cancellationToken).ConfigureAwait(false);
            _eventTracker.Track(new TranslationEvent
            {
                RequestId = Guid.NewGuid().ToString("N"),
                SessionId = _trackingSession.SessionId,
                PoiCode = code,
                Language = targetLang,
                UserType = ctx.UserType,
                UserId = ctx.UserId,
                DeviceId = ctx.DeviceId,
                Status = TranslationEventStatus.AppEvent,
                DurationMs = 0,
                Timestamp = DateTimeOffset.UtcNow,
                Source = "local_cache",
                ActionType = EventActionKind.Navigate,
                NetworkType = NetworkTypeResolver.Resolve(),
                FetchTriggered = false,
                UserApproved = null,
                Latitude = geoPoi.Latitude,
                Longitude = geoPoi.Longitude,
                GeoRadiusMeters = geoPoi.Radius > 0 ? geoPoi.Radius : null,
                GeoSource = EventGeoSource.Db,
                BatchItemCount = null
            });
        }
        catch
        {
            // analytics only
        }
    }

    private async Task<Poi?> GetTranslationSourcePoiAsync(string code, CancellationToken ct)
    {
        // Source base geo data from the database.
        var core = await _poiQuery.GetByCodeAsync(code, null, ct).ConfigureAwait(false);
        if (core == null) return null;

        // Fetch "vi" baseline text directly from the synchronous in-memory lookup.
        var result = _locService.GetLocalizationResult(core.Code, "vi");
        if (result.Localization != null)
        {
            var poi = new Poi
            {
                Id = $"{core.Code.Trim()}_vi",
                Code = core.Code.Trim(),
                Latitude = core.Latitude,
                Longitude = core.Longitude,
                Radius = core.Radius,
                Priority = core.Priority,
                Localization = new PoiLocalization
                {
                    Code = core.Code.Trim(),
                    LanguageCode = "vi",
                    Name = result.Localization.Name ?? "",
                    Summary = result.Localization.Summary ?? "",
                    NarrationShort = result.Localization.NarrationShort ?? "",
                    NarrationLong = result.Localization.NarrationLong ?? ""
                }
            };
            return poi;
        }

        return core; // No text available to translate
    }

    private class PendingTranslationRequest
    {
        public string Code { get; set; } = string.Empty;
        public string FromLang { get; set; } = string.Empty;
        public string TargetLang { get; set; } = string.Empty;
        public PoiLocalization SrcLoc { get; set; } = new();
        public TaskCompletionSource<PoiTranslationCacheEntry?> Tcs { get; set; } = new();
    }

    private readonly object _batchQueueLock = new();
    private List<PendingTranslationRequest> _currentBatch = new();
    private bool _batchScheduled = false;

    private async Task<PoiTranslationCacheEntry?> ExecuteTranslationBatchAsync(string code, string fromLang, string targetLang, PoiLocalization srcLoc, CancellationToken ct)
    {
        var req = new PendingTranslationRequest
        {
            Code = code,
            FromLang = fromLang,
            TargetLang = targetLang,
            SrcLoc = srcLoc,
            Tcs = new TaskCompletionSource<PoiTranslationCacheEntry?>(TaskCreationOptions.RunContinuationsAsynchronously)
        };

        List<PendingTranslationRequest>? batchToRun = null;

        lock (_batchQueueLock)
        {
            _currentBatch.Add(req);
            if (_currentBatch.Count >= 5)
            {
                batchToRun = _currentBatch;
                _currentBatch = new();
                _batchScheduled = false;
            }
            else if (!_batchScheduled)
            {
                _batchScheduled = true;
                _ = ScheduleBatchDrainingAsync();
            }
        }

        if (batchToRun != null)
        {
            _ = ProcessBatchAsync(batchToRun);
        }

        using var reg = ct.Register(() => req.Tcs.TrySetCanceled());
        return await req.Tcs.Task.ConfigureAwait(false);
    }

    private async Task ScheduleBatchDrainingAsync()
    {
        await Task.Delay(100).ConfigureAwait(false);
        List<PendingTranslationRequest>? batchToRun = null;
        lock (_batchQueueLock)
        {
            if (_currentBatch.Count > 0)
            {
                batchToRun = _currentBatch;
                _currentBatch = new();
            }
            _batchScheduled = false;
        }
        if (batchToRun != null)
        {
            _ = ProcessBatchAsync(batchToRun);
        }
    }

    private async Task ProcessBatchAsync(List<PendingTranslationRequest> batch)
    {
        await _globalLimit.WaitAsync().ConfigureAwait(false);
        try
        {
            var apiRequests = new List<TranslationRequest>();
            foreach (var req in batch)
            {
                apiRequests.Add(new TranslationRequest { Id = $"{req.Code}_Name", Text = req.SrcLoc.Name ?? "", FromLang = req.FromLang, ToLang = req.TargetLang });
                apiRequests.Add(new TranslationRequest { Id = $"{req.Code}_Summary", Text = req.SrcLoc.Summary ?? "", FromLang = req.FromLang, ToLang = req.TargetLang });
                apiRequests.Add(new TranslationRequest { Id = $"{req.Code}_NarrationShort", Text = req.SrcLoc.NarrationShort ?? "", FromLang = req.FromLang, ToLang = req.TargetLang });
                apiRequests.Add(new TranslationRequest { Id = $"{req.Code}_NarrationLong", Text = req.SrcLoc.NarrationLong ?? "", FromLang = req.FromLang, ToLang = req.TargetLang });
            }

            List<TranslationResult> results;
            try
            {
                _logger.LogInformation($"[TranslationTrigger] Processing batch of {batch.Count} POIs ({apiRequests.Count} segments).");
                results = await _translator.TranslateBatchAsync(apiRequests).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"[TRANSLATE] Batch exception: {ex.Message}");
                results = apiRequests.Select(r => new TranslationResult(r.Text, false)).ToList();
            }

            if (results == null || results.Count != apiRequests.Count)
            {
                 results = apiRequests.Select(r => new TranslationResult(r.Text, false)).ToList();
            }

            var idx = 0;
            foreach (var r in batch)
            {
                var nameR = results[idx++];
                var summaryR = results[idx++];
                var narrSR = results[idx++];
                var narrLR = results[idx++];

                var allSucceeded = nameR.Succeeded && summaryR.Succeeded && narrSR.Succeeded && narrLR.Succeeded;

                var key = PoiTranslationCacheEntry.MakeKey(r.Code, r.TargetLang);
                var entry = new PoiTranslationCacheEntry
                {
                    Key = key,
                    Code = r.Code,
                    LanguageCode = r.TargetLang,
                    Name = nameR.Text,
                    Summary = summaryR.Text,
                    NarrationShort = narrSR.Text,
                    NarrationLong = narrLR.Text,
                    IsAutoGenerated = allSucceeded,
                    CreatedAt = DateTime.UtcNow
                };
                r.Tcs.TrySetResult(entry);
            }
        }
        catch(Exception e)
        {
            foreach (var req in batch) req.Tcs.TrySetException(e);
        }
        finally
        {
            _globalLimit.Release();
        }
    }
}
