using System.Collections.Concurrent;
using System.Threading;
using MauiApp1.Models;


using System.Diagnostics;
namespace MauiApp1.Services;

public sealed class PoiTranslationService : IPoiTranslationService
{
    private readonly PoiDatabase _db;
    private readonly ITranslationProvider _translator;
    private readonly LocalizationService _locService;

    private static string NormalizeLang(string? lang) =>
        string.IsNullOrWhiteSpace(lang) ? "vi" : lang.Trim().ToLowerInvariant();

    private readonly ConcurrentDictionary<string, SemaphoreSlim> _locks = new();

    public PoiTranslationService(PoiDatabase db, ITranslationProvider translator, LocalizationService locService)
    {
        _db = db;
        _translator = translator;
        _locService = locService;
    }

    /// <inheritdoc />
    public async Task<Poi?> GetOrTranslateAsync(string code, string? lang, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(code))
            return null;

        code = code.Trim().ToUpperInvariant();

        await _db.InitAsync().ConfigureAwait(false);

        var targetLang = NormalizeLang(lang);

        // 1) Exact row in main POI table (same behavior as "have this language" without touching fallback order here)
        var direct = await _db.GetExactByCodeAndLanguageAsync(code, targetLang, cancellationToken).ConfigureAwait(false);
        if (direct != null)
            return direct;

        var key = PoiTranslationCacheEntry.MakeKey(code, targetLang);
        Debug.WriteLine($"[TRANSLATE] GetOrTranslateAsync start code={code} target={targetLang}");
        var gate = _locks.GetOrAdd(key, _ => new SemaphoreSlim(1, 1));
        var entered = false;
        await gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        entered = true;
        try
        {
            // 2) Re-check primary table (another thread may have inserted)
            direct = await _db.GetExactByCodeAndLanguageAsync(code, targetLang, cancellationToken).ConfigureAwait(false);
            if (direct != null)
                return direct;

            // 3) Cache
            var cached = await _db.GetTranslationCacheAsync(code, targetLang, cancellationToken).ConfigureAwait(false);
            if (cached != null)
            {
                Debug.WriteLine($"[TRANSLATE] Cache hit key={cached.Key}");
                var sourceForGeo = await GetTranslationSourcePoiAsync(code, cancellationToken).ConfigureAwait(false);
                if (sourceForGeo == null)
                    return null;
                return MergeCachedTextWithSourcePoi(sourceForGeo, cached, targetLang, cached.IsAutoGenerated);
            }
            Debug.WriteLine($"[TRANSLATE] Cache miss key={key}");

            // 4) Source POI: prefer EN, else any row for code
            var source = await GetTranslationSourcePoiAsync(code, cancellationToken).ConfigureAwait(false);
            if (source == null)
                return null;

            var fromLang = source.Localization?.LanguageCode ?? "vi"; 
            if (fromLang == targetLang)
                return source;

            Debug.WriteLine($"[TRANSLATE] Translating code={code} from={fromLang} to={targetLang}");
            TranslationResult nameR;
            TranslationResult summaryR;
            TranslationResult narrSR;
            TranslationResult narrLR;

            var srcLoc = source.Localization;
            if (srcLoc == null)
            {
                Debug.WriteLine($"[TRANSLATE] Source localization is null for {code}, using empty strings");
                srcLoc = new PoiLocalization { Name = "", Summary = "", NarrationShort = "", NarrationLong = "" };
            }

            try { nameR = await _translator.TranslateAsync(srcLoc.Name, fromLang, targetLang, cancellationToken).ConfigureAwait(false); }
            catch (Exception ex) { Debug.WriteLine($"[TRANSLATE] Translate name exception: {ex.Message}"); nameR = new TranslationResult(srcLoc.Name, false); }

            try { summaryR = await _translator.TranslateAsync(srcLoc.Summary, fromLang, targetLang, cancellationToken).ConfigureAwait(false); }
            catch (Exception ex) { Debug.WriteLine($"[TRANSLATE] Translate summary exception: {ex.Message}"); summaryR = new TranslationResult(srcLoc.Summary, false); }

            try { narrSR = await _translator.TranslateAsync(srcLoc.NarrationShort, fromLang, targetLang, cancellationToken).ConfigureAwait(false); }
            catch (Exception ex) { Debug.WriteLine($"[TRANSLATE] Translate narrationShort exception: {ex.Message}"); narrSR = new TranslationResult(srcLoc.NarrationShort, false); }

            try { narrLR = await _translator.TranslateAsync(srcLoc.NarrationLong, fromLang, targetLang, cancellationToken).ConfigureAwait(false); }
            catch (Exception ex) { Debug.WriteLine($"[TRANSLATE] Translate narrationLong exception: {ex.Message}"); narrLR = new TranslationResult(srcLoc.NarrationLong, false); }

            var allSucceeded = nameR.Succeeded && summaryR.Succeeded && narrSR.Succeeded && narrLR.Succeeded;

            //var allSucceeded = nameR.Succeeded && summaryR.Succeeded && narrSR.Succeeded && narrLR.Succeeded;

            var entry = new PoiTranslationCacheEntry
            {
                Key = key,
                Code = source.Code.Trim(),
                LanguageCode = targetLang,
                Name = nameR.Text,
                Summary = summaryR.Text,
                NarrationShort = narrSR.Text,
                NarrationLong = narrLR.Text,
                IsAutoGenerated = allSucceeded,
                CreatedAt = DateTime.UtcNow
            };
            if (allSucceeded)
            {
                Debug.WriteLine($"[TRANSLATE] All segments succeeded, caching key={key}");
                await _db.UpsertTranslationCacheAsync(entry, cancellationToken).ConfigureAwait(false);
            }
            else
            {
                Debug.WriteLine($"[TRANSLATE] Partial/failed translation for code={code} to {targetLang}; skipping cache");
            }

            Debug.WriteLine($"[TRANSLATE] Returning merged poi for code={code} target={targetLang} succeeded={allSucceeded}");
            return MergeCachedTextWithSourcePoi(source, entry, targetLang, allSucceeded);
        }
        finally
        {
            if (entered)
            {
                try { gate.Release(); } catch { }
            }
        }
    }

    private static Poi MergeCachedTextWithSourcePoi(Poi source, PoiTranslationCacheEntry cached, string targetLang, bool isAutoTranslated)
    {
        var poi = new Poi
        {
            Id = $"{source.Code.Trim()}_{targetLang}",
            Code = source.Code.Trim(),
            Latitude = source.Latitude,
            Longitude = source.Longitude,
            Radius = source.Radius,
            Priority = source.Priority,
            IsAutoTranslated = isAutoTranslated,
            Localization = new PoiLocalization
            {
                Code = source.Code.Trim(),
                LanguageCode = targetLang,
                Name = cached.Name,
                Summary = cached.Summary,
                NarrationShort = cached.NarrationShort,
                NarrationLong = cached.NarrationLong
            }
        };

        return poi;
    }

    private async Task<Poi?> GetTranslationSourcePoiAsync(string code, CancellationToken ct)
    {
        // Source base geo data from the database.
        var core = await _db.GetByCodeAsync(code).ConfigureAwait(false);
        if (core == null) return null;

        // Fetch "vi" baseline text directly from the synchronous in-memory lookup.
        var result = _locService.GetLocalizationResult(core.Code, "vi");
        if (result.Localization != null)
        {
            var poi = new Poi
            {
                Id = $"{core.Code.Trim()}_vi",
                Code = core.Code.Trim(),
                Latitude = core.Latitude,
                Longitude = core.Longitude,
                Radius = core.Radius,
                Priority = core.Priority,
                Localization = new PoiLocalization
                {
                    Code = core.Code.Trim(),
                    LanguageCode = "vi",
                    Name = result.Localization.Name ?? "",
                    Summary = result.Localization.Summary ?? "",
                    NarrationShort = result.Localization.NarrationShort ?? "",
                    NarrationLong = result.Localization.NarrationLong ?? ""
                }
            };
            return poi;
        }

        return core; // No text available to translate
    }
}
