using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MauiApp1.Models;
using MauiApp1.ApplicationContracts.Repositories;
using Microsoft.Extensions.Logging;

namespace MauiApp1.Services;

public interface ISmartCacheManager
{
    Task<ResolvedPoiContent?> GetAsync(string poiCode, string lang, int baseVersion, int transVersion, string mode, string traceId);
    Task SetAsync(string poiCode, string lang, ResolvedPoiContent content, int baseVersion, int transVersion, string mode, string traceId);
    void ClearL1();
}

public class SmartCacheManager : ISmartCacheManager
{
    // 3. THREAD-SAFE LRU CACHE
    private readonly Dictionary<string, (ResolvedPoiContent Content, DateTime Expiry)> _l1Cache = new();
    private readonly LinkedList<string> _l1Order = new();
    private readonly object _l1Lock = new();
    private const int MaxL1Entries = 100;
    private readonly TimeSpan _l1Ttl = TimeSpan.FromMinutes(10);
    
    private readonly ITranslationRepository _l2Cache;
    private readonly ILogger<SmartCacheManager> _logger;

    public SmartCacheManager(ITranslationRepository l2Cache, ILogger<SmartCacheManager> logger)
    {
        _l2Cache = l2Cache;
        _logger = logger;
    }

    public async Task<ResolvedPoiContent?> GetAsync(string poiCode, string lang, int baseVersion, int transVersion, string mode, string traceId)
    {
        string key = PoiTranslationCacheEntry.MakeKey(poiCode, lang, baseVersion, transVersion, mode);

        // 1. L1: Memory Cache (Lock-protected LRU)
        lock (_l1Lock)
        {
            if (_l1Cache.TryGetValue(key, out var cached))
            {
                if (cached.Expiry > DateTime.UtcNow)
                {
                    // Move to front of LRU (Promotion)
                    _l1Order.Remove(key);
                    _l1Order.AddFirst(key);
                    _logger.LogDebug("CACHE_HIT_L1 | traceId: {TraceId} | Key: {Key}", traceId, key);
                    return cached.Content;
                }
                else
                {
                    _l1Cache.Remove(key);
                    _l1Order.Remove(key);
                    _logger.LogInformation("CACHE_INVALIDATED | traceId: {TraceId} | reason: ttl_expired | Key: {Key}", traceId, key);
                }
            }
        }

        // 2. L2: SQLite Cache (Persistent)
        var entry = await _l2Cache.GetTranslationCacheAsync(poiCode, lang);
        if (entry != null)
        {
            // 7. L3 CACHE STRICT RULE
            // MUST re-resolve on version mismatch
            if (entry.BaseVersion == baseVersion && entry.TranslationVersion == transVersion && entry.Mode == mode)
            {
                _logger.LogInformation("CACHE_HIT_L2 | traceId: {TraceId} | Key: {Key}", traceId, key);
                var content = MapFromCache(entry);
                
                // Promote to L1
                SetL1(key, content, traceId);
                return content;
            }
            else
            {
                _logger.LogWarning("CACHE_INVALIDATED | traceId: {TraceId} | reason: version_mismatch | Key: {Key} | Required: v{BV}.t{TV} | Found: v{EBV}.t{ETV}", 
                    traceId, key, baseVersion, transVersion, entry.BaseVersion, entry.TranslationVersion);
            }
        }
        else
        {
            _logger.LogInformation("CACHE_MISS_L2 | traceId: {TraceId} | Key: {Key}", traceId, key);
        }

        return null;
    }

    public async Task SetAsync(string poiCode, string lang, ResolvedPoiContent content, int baseVersion, int transVersion, string mode, string traceId)
    {
        string key = PoiTranslationCacheEntry.MakeKey(poiCode, lang, baseVersion, transVersion, mode);

        // Update L1
        SetL1(key, content, traceId);

        // Update L2
        var entry = new PoiTranslationCacheEntry
        {
            Key = key,
            Code = poiCode,
            LanguageCode = lang,
            Mode = mode,
            Name = content.Name,
            Summary = content.Summary,
            NarrationShort = content.NarrationShort,
            NarrationLong = content.NarrationLong,
            BaseVersion = baseVersion,
            TranslationVersion = transVersion,
            IsAutoGenerated = content.ShowBadgeAutoTranslated,
            CreatedAt = DateTime.UtcNow
        };

        await _l2Cache.UpsertTranslationCacheAsync(entry);
        _logger.LogDebug("CACHE_LAYER_SET_L2 | traceId: {TraceId} | Key: {Key}", traceId, key);
    }

    private void SetL1(string key, ResolvedPoiContent content, string traceId)
    {
        lock (_l1Lock)
        {
            if (_l1Cache.ContainsKey(key))
            {
                _l1Order.Remove(key);
            }
            else if (_l1Cache.Count >= MaxL1Entries)
            {
                // Evict LRU
                var last = _l1Order.Last.Value;
                _l1Cache.Remove(last);
                _l1Order.RemoveLast();
                _logger.LogInformation("CACHE_EVICTION_L1 | traceId: {TraceId} | Key: {Key}", traceId, last);
            }

            _l1Cache[key] = (content, DateTime.UtcNow.Add(_l1Ttl));
            _l1Order.AddFirst(key);
        }
    }

    private ResolvedPoiContent MapFromCache(PoiTranslationCacheEntry c)
    {
        return new ResolvedPoiContent
        {
            Name = c.Name,
            Summary = c.Summary,
            NarrationShort = c.NarrationShort,
            NarrationLong = c.NarrationLong,
            SourceType = "cache",
            IsFallback = false,
            ConfidenceScore = 1.0,
            ShowBadgeAutoTranslated = c.IsAutoGenerated,
            ShowBadgeOutdated = false,
            DominantSource = "cache"
        };
    }

    public void ClearL1()
    {
        lock (_l1Lock)
        {
            _l1Cache.Clear();
            _l1Order.Clear();
        }
    }
}
