using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ContractSourceGenerator;

internal static class ContractEmitter
{
    public static string EmitAll(ContractSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace GeneratedContract;");
        sb.AppendLine();
        EmitConstants(sb, spec);
        sb.AppendLine();
        EmitEnums(sb, spec);
        sb.AppendLine();
        EmitDto(sb, spec);
        sb.AppendLine();
        EmitValidator(sb, spec);
        sb.AppendLine();
        EmitJsonSchemaConst(sb, spec);
        return sb.ToString();
    }

    private static void EmitConstants(StringBuilder sb, ContractSpec spec)
    {
        sb.AppendLine("/// <summary>Canonical contract version constants (generated from ContractDefinition).</summary>");
        sb.AppendLine("public static class EventContractV1");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string Version = \"{EscapeString(spec.Version)}\";");
        sb.AppendLine($"    public const string VersionPropertyName = \"{EscapeString(spec.VersionPropertyName)}\";");
        sb.AppendLine("}");
    }

    private static void EmitEnums(StringBuilder sb, ContractSpec spec)
    {
        foreach (var en in spec.Enums)
        {
            sb.AppendLine("/// <summary>Wire enum (JSON string values per member).</summary>");
            sb.AppendLine($"public enum {en.Name}");
            sb.AppendLine("{");
            for (var i = 0; i < en.Members.Count; i++)
            {
                var m = en.Members[i];
                if (i == 0)
                    sb.AppendLine($"    {m.ClrName} = 0,");
                else
                    sb.AppendLine($"    {m.ClrName},");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private static void EmitDto(StringBuilder sb, ContractSpec spec)
    {
        sb.AppendLine("/// <summary>Ingestion / wire DTO for EventContractV1 (generated).</summary>");
        sb.AppendLine("public sealed class EventContractV1Dto");
        sb.AppendLine("{");
        foreach (var f in spec.Fields)
        {
            sb.AppendLine($"    [JsonPropertyName(\"{EscapeString(f.JsonName)}\")]");
            sb.AppendLine($"    public {ClrPropertyType(f)} {f.PropertyName} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static string ClrPropertyType(WireFieldModel f)
    {
        var core = f.Clr switch
        {
            ClrWireKindModel.String => "string",
            ClrWireKindModel.Int64 => "long",
            ClrWireKindModel.Int32 => "int",
            ClrWireKindModel.Double => "double",
            ClrWireKindModel.Boolean => "bool",
            ClrWireKindModel.DateTimeOffset => "DateTimeOffset",
            ClrWireKindModel.Enum => f.EnumTypeName ?? throw new InvalidOperationException($"Enum field '{f.JsonName}' missing EnumTypeName."),
            _ => throw new InvalidOperationException(f.Clr.ToString())
        };

        if (f.Clr == ClrWireKindModel.Enum)
            return core;

        return f.Nullable ? core + "?" : core;
    }

    private static void EmitValidator(StringBuilder sb, ContractSpec spec)
    {
        sb.AppendLine("/// <summary>Ingestion validation for EventContractV1 (generated; mirrors pre-6.7.4 rules).</summary>");
        sb.AppendLine("public static class EventContractValidator");
        sb.AppendLine("{");
        sb.AppendLine("    public static string? GetRejectReason(EventContractV1Dto e)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!string.IsNullOrWhiteSpace(e.ContractVersion) &&");
        sb.AppendLine("            !string.Equals(e.ContractVersion.Trim(), EventContractV1.Version, StringComparison.Ordinal))");
        sb.AppendLine("            return $\"contractVersion must be '{EventContractV1.Version}' or omitted\";");
        sb.AppendLine();
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(e.EventId))");
        sb.AppendLine("            return \"eventId is required\";");
        sb.AppendLine();
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(e.RequestId))");
        sb.AppendLine("            return \"requestId is required\";");
        sb.AppendLine();
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(e.SessionId))");
        sb.AppendLine("            return \"sessionId is required\";");
        sb.AppendLine();
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(e.DeviceId))");
        sb.AppendLine("            return \"deviceId is required\";");
        sb.AppendLine();
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(e.Status))");
        sb.AppendLine("            return \"status is required\";");
        sb.AppendLine();
        sb.AppendLine("        if (e.Timestamp == default)");
        sb.AppendLine("            return \"timestamp must be a valid non-default ISO-8601 instant\";");
        sb.AppendLine();
        sb.AppendLine("        if (e.DurationMs < 0)");
        sb.AppendLine("            return \"durationMs must be >= 0\";");
        sb.AppendLine();
        sb.AppendLine("        if (!Enum.IsDefined(typeof(EventActionKind), e.ActionType))");
        sb.AppendLine("            return \"actionType is not a defined enum value\";");
        sb.AppendLine();
        sb.AppendLine("        if (!Enum.IsDefined(typeof(EventGeoSource), e.GeoSource))");
        sb.AppendLine("            return \"geoSource is not a defined enum value\";");
        sb.AppendLine();
        sb.AppendLine("        if (e.GeoSource != EventGeoSource.Unknown)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (e.Latitude is null || e.Longitude is null)");
        sb.AppendLine("                return \"latitude and longitude are required when geoSource is not unknown\";");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var src = (e.Source ?? \"\").Trim();");
        sb.AppendLine("        var isBatchStyle = string.Equals(src, \"nearby_sync\", StringComparison.OrdinalIgnoreCase) ||");
        sb.AppendLine("                           e.BatchItemCount.HasValue;");
        sb.AppendLine();
        sb.AppendLine("        if (!isBatchStyle)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrWhiteSpace(e.PoiCode))");
        sb.AppendLine("                return \"poiCode is required unless source is nearby_sync or batchItemCount is set\";");
        sb.AppendLine();
        sb.AppendLine("            if (string.IsNullOrWhiteSpace(e.Language))");
        sb.AppendLine("                return \"language is required unless source is nearby_sync or batchItemCount is set\";");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitJsonSchemaConst(StringBuilder sb, ContractSpec spec)
    {
        var json = BuildJsonSchema(spec);
        sb.AppendLine("/// <summary>JSON Schema (draft 2020-12) generated from the same contract spec as the DTO.</summary>");
        sb.AppendLine("public static class EventContractV1JsonSchema");
        sb.AppendLine("{");
        sb.AppendLine("    public const string Draft202012 =");
        sb.AppendLine("\"\"\"");
        sb.Append(json);
        sb.AppendLine("\"\"\";");
        sb.AppendLine("}");
    }

    private static string BuildJsonSchema(ContractSpec spec)
    {
        var j = new StringBuilder();
        j.AppendLine("{");
        j.AppendLine("  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",");
        j.AppendLine("  \"$id\": \"https://vn-go-travel.local/schemas/EventContractV1.generated.json\",");
        j.AppendLine("  \"title\": \"EventContractV1\",");
        j.AppendLine("  \"type\": \"object\",");
        j.AppendLine("  \"additionalProperties\": false,");
        j.AppendLine("  \"properties\": {");
        var first = true;
        foreach (var f in spec.Fields)
        {
            if (!first)
                j.AppendLine(",");
            first = false;
            j.Append($"    \"{EscapeJson(f.JsonName)}\": ");
            j.Append(SchemaPropertyFragment(f, spec.Enums));
        }

        j.AppendLine();
        j.AppendLine("  },");
        j.Append("  \"required\": [");
        var req = new List<string>();
        foreach (var f in spec.Fields)
        {
            if (IsRequiredInSchema(f))
                req.Add(EscapeJson(f.JsonName));
        }

        j.Append(string.Join(", ", req.Select(q => $"\"{q}\"")));
        j.AppendLine("]");
        j.AppendLine("}");
        return j.ToString();
    }

    private static bool IsRequiredInSchema(WireFieldModel f)
    {
        if (f.Nullable && f.Clr != ClrWireKindModel.Enum)
            return false;
        if (f.Clr == ClrWireKindModel.String && f.Nullable)
            return false;
        if (f.JsonName is "contractVersion")
            return false;
        return f.JsonName is "eventId" or "requestId" or "sessionId" or "deviceId" or "status" or "durationMs" or "timestamp"
            or "actionType" or "fetchTriggered" or "geoSource";
    }

    private static string SchemaPropertyFragment(WireFieldModel f, IReadOnlyList<WireEnumModel> enums)
    {
        if (f.Clr == ClrWireKindModel.Enum && f.EnumTypeName is { } enName)
        {
            var en = enums.FirstOrDefault(e => e.Name == enName);
            if (en is null)
                return "{ \"type\": \"string\" }";
            var vals = string.Join(", ", en.Members.Select(m => $"\"{EscapeJson(m.JsonWireName)}\""));
            return "{ \"type\": \"string\", \"enum\": [ " + vals + " ] }";
        }

        return f.Clr switch
        {
            ClrWireKindModel.String when f.Nullable =>
                "{ \"type\": [ \"string\", \"null\" ] }",
            ClrWireKindModel.String =>
                "{ \"type\": \"string\" }",
            ClrWireKindModel.Int64 when f.Nullable =>
                "{ \"type\": [ \"integer\", \"null\" ] }",
            ClrWireKindModel.Int64 =>
                "{ \"type\": \"integer\", \"minimum\": 0 }",
            ClrWireKindModel.Int32 when f.Nullable =>
                "{ \"type\": [ \"integer\", \"null\" ] }",
            ClrWireKindModel.Int32 =>
                "{ \"type\": \"integer\" }",
            ClrWireKindModel.Double when f.Nullable =>
                "{ \"type\": [ \"number\", \"null\" ] }",
            ClrWireKindModel.Double =>
                "{ \"type\": \"number\" }",
            ClrWireKindModel.Boolean when f.Nullable =>
                "{ \"type\": [ \"boolean\", \"null\" ] }",
            ClrWireKindModel.Boolean =>
                "{ \"type\": \"boolean\" }",
            ClrWireKindModel.DateTimeOffset =>
                "{ \"type\": \"string\", \"format\": \"date-time\" }",
            _ => "{ \"type\": \"string\" }"
        };
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string EscapeJson(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
