using SQLite;

namespace MauiApp1.Models;

/// <summary>
/// Cached auto-translated POI text. Does not replace rows in <c>pois</c>.
/// Narration is split into short/long to align with <see cref="Poi"/> (spec often refers to a single narration field).
/// </summary>
[Table("poi_translation_cache")]
public class PoiTranslationCacheEntry
{
    /// <summary>Stable key: normalized Code + "|" + normalized LanguageCode.</summary>
    [PrimaryKey]
    public string Key { get; set; } = "";

    public static string MakeKey(string code, string languageCode)
    {
        var c = string.IsNullOrWhiteSpace(code) ? "" : code.Trim().ToUpperInvariant();
        var l = string.IsNullOrWhiteSpace(languageCode) ? "vi" : languageCode.Trim().ToLowerInvariant();
        return $"{c}|{l}";
    }

    public string Code { get; set; } = "";
    public string LanguageCode { get; set; } = "";

    public string Name { get; set; } = "";
    public string Summary { get; set; } = "";

    public string NarrationShort { get; set; } = "";
    public string NarrationLong { get; set; } = "";

    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
}
